import { DesignResults, ProjectData } from "../types";
import { svgToPngDataUrl } from "./fileUtils";

declare const docx: any;

const CLIENT_SCOPE_ITEMS = [
    "All civil works",
    "Incoming pipeline up to battery limit",
    "Treated water outlet pipeline from battery limit",
    "Three-phase incoming power supply up to control panel",
    "Treated water storage and associated pumping systems",
    "Material lifting and unloading above 50 kg (using forklifts, cranes, etc.) to be arranged by the client, including site unloading",
    "Provision of network connectivity (Internet / Wi-Fi) for the control panel, if required"
];

const createHtmlTable = (headers: string[], data: (string | number)[][]) => {
    return `
        <table class="w-full text-left border-collapse">
            <thead class="bg-slate-100">
                <tr>
                    ${headers.map(header => `<th class="p-3 font-semibold text-slate-600 uppercase text-xs tracking-wider">${header}</th>`).join('')}
                </tr>
            </thead>
            <tbody>
                ${data.map(row => `
                    <tr class="border-b border-slate-200">
                        ${row.map(cell => `<td class="p-3 text-slate-700">${String(cell)}</td>`).join('')}
                    </tr>
                `).join('')}
            </tbody>
        </table>
    `;
};

const createComplianceList = (items: DesignResults['complianceChecklist']) => {
    return `
        <ul class="space-y-4">
            ${items.map(item => `
                <li class="flex items-start space-x-3 p-3 bg-slate-50 rounded-md">
                    <div class="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-white ${item.compliant ? 'bg-green-500' : 'bg-red-500'}">
                        ${item.compliant ? '✓' : '✗'}
                    </div>
                    <div>
                        <p class="font-semibold">${item.item}</p>
                        <p class="text-sm text-slate-600">${item.details}</p>
                    </div>
                </li>
            `).join('')}
        </ul>
    `;
};

export const generateHtmlReport = (results: DesignResults, projectData: ProjectData) => {
    const reportTitle = `${projectData.projectType} ${projectData.flowRate} KLD (${projectData.flowRate} m³/day)`;

    // Format summary markdown to HTML
    const formattedSummary = results.reportSummary
        .replace(/^### (.*$)/gim, '<h4 class="text-xl font-semibold mt-6 mb-2">$1</h4>')
        .replace(/^## (.*$)/gim, '<h3 class="text-2xl font-bold mt-8 mb-3">$1</h3>')
        .replace(/^# (.*$)/gim, '<h2 class="text-3xl font-bold mt-10 mb-4">$1</h2>')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\n/g, '<br />');

    // Prepare table data
    const calculationsData = results.designCalculations.map(item => [item.parameter, item.value, item.unit, item.description]);
    const bomData = results.billOfMaterials.map(item => [item.name, item.quantity, item.unit, item.vendorSuggestion]);
    const abbreviationsData = results.abbreviations.map(item => [item.term, item.definition]);

    const footerContent = projectData.fromAddress
        ? projectData.fromAddress.replace(/\n/g, '<br />')
        : 'Generated by Pampana V Rao, Email :support@thoyam.com, WhatsApp: +91 7780526667';

    // Conditionally create the header based on whether it's a proposal
    let headerBlock: string;
    if (projectData.fromAddress) {
        const addressLines = projectData.fromAddress.split('\n');
        const companyName = addressLines[0];
        const restOfAddress = addressLines.slice(1).join('<br />');
        
        headerBlock = `
            <h1 class="text-3xl font-bold text-slate-800">${companyName}</h1>
            ${restOfAddress ? `<p class="text-md text-slate-600 mt-2">${restOfAddress}</p>` : ''}
        `;
    } else {
        headerBlock = `
            <h1 class="text-4xl font-bold text-blue-700">PureFlowDesign for better World</h1>
            <h2 class="text-2xl font-semibold text-slate-800 mt-2">Preliminary Design Report</h2>
        `;
    }

    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PureFlowDesign - Design Report - ${reportTitle}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        @media print {
            body { 
                -webkit-print-color-adjust: exact; 
                print-color-adjust: exact;
            }
            .page-break { 
                page-break-before: always; 
            }
        }
        body { 
            font-family: 'Inter', sans-serif; 
        }
        .prose {
             line-height: 1.7;
        }
        .prose strong {
            font-weight: 600;
        }
    </style>
</head>
<body class="bg-slate-100">
    <main class="max-w-4xl mx-auto p-4 sm:p-8 bg-white shadow-lg my-8 rounded-lg">
        <header class="text-center border-b border-slate-200 pb-6 mb-8">
            ${headerBlock}
            <p class="text-lg text-slate-600 mt-4">${reportTitle}</p>
        </header>

        <section id="summary" class="mb-12">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">1. Report Summary</h3>
            <div class="prose max-w-none text-slate-700">
                ${formattedSummary}
            </div>
        </section>

        <section id="pid" class="mb-12 page-break">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">2. Process & Instrumentation Diagram (P&ID)</h3>
            <div class="border border-slate-200 rounded-lg p-4 overflow-hidden bg-slate-50">
                ${results.processFlowDiagram.svgContent}
            </div>
        </section>

        <section id="calculations" class="mb-12 page-break">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">3. Design Calculations</h3>
            ${createHtmlTable(['Parameter', 'Value', 'Unit', 'Description'], calculationsData)}
        </section>

        <section id="bom" class="mb-12 page-break">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">4. Bill of Materials (BOM)</h3>
            ${createHtmlTable(['Item Name', 'Quantity', 'Unit', 'Vendor Suggestion'], bomData)}
        </section>
        
        <section id="compliance" class="mb-12 page-break">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">5. Compliance Checklist</h3>
            ${createComplianceList(results.complianceChecklist)}
        </section>

        <section id="clientScope" class="mb-12 page-break">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">6. Client Scope / Exclusions</h3>
            <ul class="list-disc pl-8 space-y-2 text-slate-700">
                ${CLIENT_SCOPE_ITEMS.map(item => `<li>${item}</li>`).join('')}
            </ul>
        </section>

        <section id="abbreviations" class="mb-12 page-break">
            <h3 class="text-2xl font-bold border-b-2 border-blue-600 pb-2 mb-4 text-slate-800">7. Abbreviations & Acronyms</h3>
            ${createHtmlTable(['Term', 'Definition'], abbreviationsData)}
        </section>

        <footer class="text-center text-sm text-slate-500 pt-8 mt-8 border-t border-slate-200">
            <p>${footerContent}</p>
            <p class="mt-2">Generated by PureFlowDesign for better World. This is a preliminary report for reference purposes only.</p>
        </footer>
    </main>
</body>
</html>
    `;

    const slug = projectData.projectType.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');
    const filename = `PureFlowDesign-Report-${slug}-${projectData.flowRate}KLD.html`;
    
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    }, 0);
};

export const generateDocxReport = async (results: DesignResults, projectData: ProjectData) => {
    // FIX: Add a check to ensure the docx library is loaded from the window object
    // and reference window.docx directly to prevent "docx is not defined" runtime errors.
    if (typeof (window as any).docx === 'undefined') {
        console.error("docx.js library not loaded.");
        alert("Error: The document generation library (docx.js) failed to load. Please check your internet connection and try again.");
        return;
    }
    const { Packer, Document, Paragraph, TextRun, HeadingLevel, Table, TableCell, TableRow, WidthType, ImageRun, AlignmentType, ShadingType, PageBreak, Footer, PageNumber } = (window as any).docx;

    const reportTitle = `${projectData.projectType} ${projectData.flowRate} KLD (${projectData.flowRate} m³/day)`;
    const val = (value: any, def: string = ''): string => value !== undefined && value !== null ? String(value) : def;

    // --- P&ID Image ---
    let pidImage: any | undefined;
    try {
        const pngDataUrl = await svgToPngDataUrl(results.processFlowDiagram.svgContent);
        const base64Data = pngDataUrl.split(',')[1];
        pidImage = new ImageRun({
            data: Uint8Array.from(atob(base64Data), c => c.charCodeAt(0)),
            transformation: { width: 600, height: 450 },
        });
    } catch (e) {
        console.error("Could not generate P&ID image for DOCX", e);
    }

    // --- Summary Paragraphs ---
    const createStyledParagraphs = (htmlString: string): any[] => {
        const paragraphs: any[] = [];
        const lines = htmlString.replace(/<br \/>/g, '\n').split('\n');

        lines.forEach(line => {
            if (line.startsWith('<h')) {
                const level = line.match(/<h(\d)/)?.[1];
                const textContent = line.replace(/<.*?>/g, '').trim();
                let headingLevel;
                switch(level) {
                    case '4': headingLevel = HeadingLevel.HEADING_4; break;
                    case '3': headingLevel = HeadingLevel.HEADING_3; break;
                    case '2': headingLevel = HeadingLevel.HEADING_2; break;
                    default: headingLevel = HeadingLevel.HEADING_1;
                }
                 paragraphs.push(new Paragraph({ text: textContent, heading: headingLevel, spacing: { before: 200, after: 100 } }));
            } else {
                const children: any[] = [];
                const parts = line.split(/(<strong>.*?<\/strong>)/g).filter(p => p);
                 parts.forEach(part => {
                    if (part.startsWith('<strong>') && part.endsWith('</strong>')) {
                        children.push(new TextRun({ text: part.slice(8, -9), bold: true }));
                    } else {
                        children.push(new TextRun(part));
                    }
                });
                paragraphs.push(new Paragraph({ children }));
            }
        });
        return paragraphs;
    };
    
    const formattedSummaryHtml = results.reportSummary
        .replace(/^### (.*$)/gim, '<h4>$1</h4>')
        .replace(/^## (.*$)/gim, '<h3>$1</h3>')
        .replace(/^# (.*$)/gim, '<h2>$1</h2>')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\n/g, '<br />');

    const summaryParagraphs = createStyledParagraphs(formattedSummaryHtml);

    // --- Table Creation ---
    const createTable = (headers: string[], data: (string|number)[][]): any => {
        return new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
                new TableRow({
                    tableHeader: true,
                    children: headers.map(header => new TableCell({
                        shading: { fill: "E0E0E0", type: ShadingType.CLEAR, color: "auto" },
                        children: [new Paragraph({ children: [new TextRun({ text: header, bold: true })] })],
                    })),
                }),
                ...data.map(row => new TableRow({
                    children: row.map(cell => new TableCell({ children: [new Paragraph(String(cell))] }))
                }))
            ]
        });
    };
    const calcTable = createTable(['Parameter', 'Value', 'Unit', 'Description'], results.designCalculations.map(i => [val(i.parameter), val(i.value), val(i.unit), val(i.description)]));
    const bomTable = createTable(['Item Name', 'Quantity', 'Unit', 'Vendor Suggestion'], results.billOfMaterials.map(i => [val(i.name), val(i.quantity), val(i.unit), val(i.vendorSuggestion)]));
    const abbrTable = createTable(['Term', 'Definition'], results.abbreviations.map(i => [val(i.term), val(i.definition)]));

    // --- Compliance List ---
    const complianceItems = results.complianceChecklist.flatMap(item => [
        new Paragraph({
            bullet: { level: 0 },
            children: [
                new TextRun({ text: `${item.compliant ? '✓' : '✗'} ${item.item}`, bold: true, color: item.compliant ? "008000" : "FF0000" }),
            ]
        }),
        new Paragraph({
            indent: { left: 720 }, // Indent the description
            children: [new TextRun({ text: item.details, size: 20 })]
        })
    ]);
    
    // --- Client Scope List ---
    const clientScopeItemsDocx = CLIENT_SCOPE_ITEMS.map(item =>
        new Paragraph({
            bullet: { level: 0 },
            children: [new TextRun(item)],
        })
    );


    // --- Document Assembly ---
    const footerContent = projectData.fromAddress
        ? projectData.fromAddress.replace(/\n/g, ' | ')
        : 'Generated by Pampana V Rao | Email: support@thoyam.com | WhatsApp: +91 7780526667';

    const doc = new Document({
        sections: [{
            footers: {
                default: new Footer({
                    children: [new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun({ text: footerContent, size: 16 }),
                            new TextRun({ text: "  |  Page ", size: 16 }),
                            new TextRun({ children: [PageNumber.CURRENT], size: 16 }),
                        ],
                    })],
                }),
            },
            children: [
                new Paragraph({ text: "Preliminary Design Report", heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER }),
                new Paragraph({ text: reportTitle, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER, spacing: { after: 400 } }),
                
                new Paragraph({ text: "1. Report Summary", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                ...summaryParagraphs,
                
                new Paragraph({ children: [new PageBreak()] }),
                new Paragraph({ text: "2. Process & Instrumentation Diagram (P&ID)", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                pidImage ? new Paragraph({ children: [pidImage], alignment: AlignmentType.CENTER }) : new Paragraph("P&ID could not be generated."),
                
                new Paragraph({ children: [new PageBreak()] }),
                new Paragraph({ text: "3. Design Calculations", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                calcTable,
                
                new Paragraph({ children: [new PageBreak()] }),
                new Paragraph({ text: "4. Bill of Materials (BOM)", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                bomTable,
                
                new Paragraph({ children: [new PageBreak()] }),
                new Paragraph({ text: "5. Compliance Checklist", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                ...complianceItems,
                
                new Paragraph({ children: [new PageBreak()] }),
                new Paragraph({ text: "6. Client Scope / Exclusions", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                ...clientScopeItemsDocx,

                new Paragraph({ children: [new PageBreak()] }),
                new Paragraph({ text: "7. Abbreviations & Acronyms", heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
                abbrTable,
            ]
        }]
    });

    // --- Packing and Downloading ---
    const slug = projectData.projectType.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');
    const filename = `PureFlowDesign-Report-${slug}-${projectData.flowRate}KLD.doc`;

    Packer.toBlob(doc).then((blob: Blob) => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        setTimeout(() => {
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);
        }, 0);
    });
};

export const generateRtfReport = (results: DesignResults, projectData: ProjectData) => {
    // Helper to escape special RTF characters and handle Unicode
    const escapeRtf = (str: string | number) => {
        const s = String(str);
        let result = '';
        for (let i = 0; i < s.length; i++) {
            const charCode = s.charCodeAt(i);
            if (charCode <= 127) {
                result += s[i].replace(/\\/g, '\\\\').replace(/{/g, '\\{').replace(/}/g, '\\}');
            } else {
                result += `\\uc1\\u${charCode}`;
            }
        }
        return result;
    };

    const rtfHeader = `{\\rtf1\\ansi\\ansicpg1252\\deff0\\nouicompat
{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}
{\\colortbl ;\\red255\\green0\\blue0;\\red0\\green128\\blue0;}
`;

    const rtfFooter = `}`;

    const rtfHeading = (text: string, level: 1 | 2) => {
        const size = level === 1 ? 40 : 32; // H1=20pt, H2=16pt
        return `\\pard\\sa200\\sl276\\slmult1\\b\\f0\\fs${size} ${escapeRtf(text)}\\par\\pard\\b0\\fs24\\par`;
    };
    
    const rtfSummary = (summary: string) => {
        return summary
            .replace(/^### (.*$)/gim, (match, p1) => `\\pard\\sa200\\sl276\\slmult1\\b\\fs28 ${escapeRtf(p1.trim())}\\par\\pard\\b0\\fs24`)
            .replace(/^## (.*$)/gim, (match, p1) => `\\pard\\sa200\\sl276\\slmult1\\b\\fs32 ${escapeRtf(p1.trim())}\\par\\pard\\b0\\fs24`)
            .replace(/^# (.*$)/gim, (match, p1) => `\\pard\\sa200\\sl276\\slmult1\\b\\fs36 ${escapeRtf(p1.trim())}\\par\\pard\\b0\\fs24`)
            .replace(/\*\*(.*?)\*\*/g, (match, p1) => `{\\b ${escapeRtf(p1)}}`)
            .split('\n')
            .map(line => `\\pard\\sa200\\sl276\\slmult1\\fs24 ${escapeRtf(line.trim())}\\par`)
            .join('');
    };
    
    const rtfTable = (headers: string[], data: (string|number)[][], colWidths: number[] = []) => {
        let tableRtf = '';
        const totalWidth = 9000; // A4 portrait width in twips
        if(colWidths.length === 0) {
            colWidths = headers.map(() => Math.floor(totalWidth/headers.length));
        }
        
        let rowDef = '\\trowd\\trgaph108\\trleft-108';
        let currentPos = 0;
        for (const width of colWidths) {
            currentPos += width;
            rowDef += `\\clbrdrb\\brdrs\\brdrw10 \\clbrdrl\\brdrs\\brdrw10 \\clbrdrr\\brdrs\\brdrw10 \\clbrdrt\\brdrs\\brdrw10\\cellx${currentPos}`;
        }

        // Header
        tableRtf += rowDef;
        for (const header of headers) {
            tableRtf += `\\pard\\intbl\\b ${escapeRtf(header)}\\b0\\cell`;
        }
        tableRtf += '\\row';

        // Data rows
        for (const row of data) {
            tableRtf += rowDef;
            for (const cell of row) {
                tableRtf += `\\pard\\intbl ${escapeRtf(cell)}\\cell`;
            }
            tableRtf += '\\row';
        }
        
        return `{\\pard ${tableRtf}}\\pard\\par`;
    };

    const rtfComplianceList = (items: DesignResults['complianceChecklist']) => {
        return items.map(item => {
            const symbol = item.compliant ? `{\\cf2 \\u9713?}` : `{\\cf1 \\u10007?}`; // green checkmark (U+2713), red X (U+2717)
            const text = `{\\pard\\fi-360\\li720 ${symbol} {\\b ${escapeRtf(item.item)}}\\par}`;
            const details = `{\\pard\\li720\\fs20\\i ${escapeRtf(item.details)}\\i0\\par\\par}`;
            return text + details;
        }).join('');
    };

    let rtfContent = rtfHeader;
    
    rtfContent += `{\\header\\pard\\qr\\fs20 Generated by PureFlowDesign for better World\\par}`;
    rtfContent += `{\\footer\\pard\\qc\\fs20 Page \\chpgn\\par}`;

    const reportTitle = `${projectData.projectType} ${projectData.flowRate} KLD (${projectData.flowRate} m³/day)`;
    rtfContent += `{\\pard\\qc\\b\\fs48 ${escapeRtf(reportTitle)}\\par\\par}`;

    // 1. Summary
    rtfContent += rtfHeading('1. Report Summary', 1);
    rtfContent += rtfSummary(results.reportSummary);
    
    // 2. P&ID
    rtfContent += `\\page ${rtfHeading('2. Process & Instrumentation Diagram (P&ID)', 1)}`;
    rtfContent += `\\pard\\sa200\\sl276\\slmult1\\fs24\\i Note: The P&ID is a complex graphical element. For the best viewing experience, please refer to the HTML or DOCX version of this report.\\i0\\par`;

    // 3. Calculations
    const calculationsData = results.designCalculations.map(item => [item.parameter, item.value, item.unit, item.description]);
    rtfContent += `\\page ${rtfHeading('3. Design Calculations', 1)}`;
    rtfContent += rtfTable(['Parameter', 'Value', 'Unit', 'Description'], calculationsData, [2500, 1000, 1000, 4500]);

    // 4. BOM
    const bomData = results.billOfMaterials.map(item => [item.name, item.quantity, item.unit, item.vendorSuggestion]);
    rtfContent += `\\page ${rtfHeading('4. Bill of Materials (BOM)', 1)}`;
    rtfContent += rtfTable(['Item Name', 'Quantity', 'Unit', 'Vendor Suggestion'], bomData, [3000, 1000, 1000, 4000]);
    
    // 5. Compliance
    rtfContent += `\\page ${rtfHeading('5. Compliance Checklist', 1)}`;
    rtfContent += rtfComplianceList(results.complianceChecklist);

    // 6. Client Scope
    rtfContent += `\\page ${rtfHeading('6. Client Scope / Exclusions', 1)}`;
    CLIENT_SCOPE_ITEMS.forEach(item => {
        rtfContent += `{\\pard\\fi-360\\li720{\\pntext\\f0\\'B7\\tab}${escapeRtf(item)}\\par}`;
    });
    rtfContent += `\\pard\\par`;

    // 7. Abbreviations
    const abbreviationsData = results.abbreviations.map(item => [item.term, item.definition]);
    rtfContent += `\\page ${rtfHeading('7. Abbreviations & Acronyms', 1)}`;
    rtfContent += rtfTable(['Term', 'Definition'], abbreviationsData, [2000, 7000]);
    
    rtfContent += rtfFooter;

    const slug = projectData.projectType.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');
    const filename = `PureFlowDesign-Report-${slug}-${projectData.flowRate}KLD.rtf`;
    
    const blob = new Blob([rtfContent], { type: 'application/rtf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    }, 0);
};